### ISSUE TITLE
Feature Extraction

### ISSUE THREAD

**Issue by soodarama** [aaravindravi/TransferLearning_CNN_Facial_Expression_Recognition#1]
Hi Aravind,

Thanks for the codes here - they work brilliantly!
Just a quick clarification - notice that the input dataset is being read in a loop during each layer model. Is that necessary? Should they not be read just once? Isn't that a computational cost?

Will be good to hear your response.
Thanks - Sooda

**Comment by aaravindravi** [comment]
Hi Sooda,

Nice to see that this is helpful. The data is being read in this way because I was also looking at the feature outputs after each block pool layer and then comparing the results of features extracted from each layer with the classifier. I am saving each block pool layer's output into a numpy array. If you are planning to use only the last layer's output, then you can modify the code to have only the last layer.

Hope this helps.

All the best.
Aravind Ravi
